#!/bin/bash
### BEGIN INIT INFO
# Provides: wakeonlan
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start wakeonlan
### END INIT INFO
/sbin/ethtool -s CURRENT_LAN_DEVICE_NAME wol g
exit