#!/bin/bash

LANG="ja_JP.UTF-8"
LOOP=0
lecho "BEFORE_DELETE_CMD SIGNAL_CODE: ${SIGNAL_CODE}"
lecho "BEFORE_DELETE_CMD INI_FILE_DIR_PATH: ${INI_FILE_DIR_PATH}"
lecho "BEFORE_DELETE_CMD EXECUTE_FILE_NAME: ${EXECUTE_FILE_NAME}"
DELETE_FILE_PATH="${INI_FILE_DIR_PATH}/${EXECUTE_FILE_NAME}"
delete_cmd
SIGNAL_CODE=${INDEX_CODE}
lecho "AFTER_DELETE_CMD SIGNAL_CODE: ${SIGNAL_CODE}"