#!/bin/bash


# lecho "BEFORE_CREATE_ADD_COMMAND_FORM SIGNAL_CODE: ${SIGNAL_CODE}"
CHDIR_LOOP=0
CREATE_CHDIR_PATH=""
create_chdir_command_form
# lecho "BEFORE_CREATE_ADD_COMMAND_FORM SIGNAL_CODE: ${SIGNAL_CODE}"
# lecho "CREATE_CHDIR_PATH: ${CREATE_CHDIR_PATH}"
case "${SIGNAL_CODE}" in 
	"${CHECK_ERR_CODE}") ;;
	*) add_chdir_cmd_ini_file "${CREATE_CHDIR_PATH}" ;;
esac
SIGNAL_CODE=${INDEX_CODE}
# lecho "AFTER_ADD_CMD_INI_FILE SIGNAL_CODE: ${SIGNAL_CODE}"
